name: "Make README.md and index.jsom"
description: 'Makes README.md and index.json on push or pull request events for the "main" branch or when manually triggered'
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install glob2
        pip install tqdm
        pip install nbformat
      shell: bash
    - name: Make README.md and index.json files
      working-directory: ./notebook_examples
      id: make_readme_and_index
      run: python make_readme.py
      shell: bash
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: auto commit README.md and index.json
        default_author: github_actions
        committer_name: GitHub Actions
        committer_email: actions@github.com
