name: "AI Hub Feedback"
description: "Share feedback, bugs, or improvement suggestions for AI Hub - Models and Solutions Explorer"
title: "[AI Hub] "
labels: ["feedback", "AI Hub", "Models Explorer", "Solutions Explorer"]
body:
  - type: markdown
    attributes:
      value: |
        👋 Thank you for using **AI Hub**!
        Please help us improve by sharing your feedback below.

  - type: dropdown
    id: feedback_type
    attributes:
      label: Feedback Type
      options:
        - Model request
        - Solution request
        - AI Hub Feature request
        - General feedback/Bug report
    validations:
      required: true

  - type: textarea
    id: feedback_summary
    attributes:
      label: Summary
      placeholder: "Brief summary of your feedback"
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      placeholder: "Any additional context, logs, or screenshots?"
