create table DOCUMENTS
("ID" NUMBER NOT NULL,
"NAME" VARCHAR2(100) NOT NULL,
PRIMARY KEY ("ID")
);

create table CHUNKS
(ID VARCHAR2(64) NOT NULL,
CHUNK CLOB,
PAGE_NUM VARCHAR2(10),
DOCUMENTS_ID NUMBER,
PRIMARY KEY ("ID"),
CONSTRAINT fk_book
        FOREIGN KEY (DOCUMENTS_ID)
        REFERENCES DOCUMENTS (ID)
);

create table VECTORS
("ID" VARCHAR2(64) NOT NULL,
"VEC" VECTOR(768, FLOAT64),
PRIMARY KEY ("ID")
);
