[project]
name = "redis-mcp-server"
version = "0.1.0"
description = "Redis MCP Server, by Redis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.5.0",
    "redis>=5.2.1",
    "dotenv>=0.9.9",
    "numpy>=2.2.4",
]
