FROM nvcr.io/nvidia/pytorch:22.12-py3
ARG DEBIAN_FRONTEND=noninteractive

RUN pip uninstall -y torch && pip install vllm flask

RUN apt-get update && apt-get -y install tzdata && apt-get install -y nginx && apt-get install -y curl

ENV NGINX_ROOT=/etc/nginx
ENV NGINX_PID=/var/run/nginx.pid
ENV NGINX_BIN=/usr/sbin/nginx
ENV NGINX_USER=root

COPY start-vllm.sh /etc/start.sh
RUN chmod a+x /etc/start.sh
COPY vllm-log-config.yaml /etc/vllm-log-config.yaml
ENV UVICORN_LOG-CONFIG=/etc/vllm-log-config.yaml
ENV UVICORN_LOG_CONFIG=/etc/vllm-log-config.yaml

EXPOSE 5001

COPY nginx.conf /etc/nginx/nginx.conf
COPY vllm-api-server.py /etc/vllm-api-server.py
WORKDIR /home/datascience

ENTRYPOINT [ "/bin/bash", "--login",  "-c"]
CMD ["/etc/start.sh"]
